version: "3"
services:

  site:
    image: ghcr.io/angulardart-community/site:latest
    build:
      context: .
      target: site
    command: ["make", "serve"]
    environment:
      - JEKYLL_ENV=development
      - JEKYLL_SITE_HOST=0.0.0.0
      - JEKYLL_SITE_PORT=5000
      - NODE_ENV=development
    ports:
      - "5000:5000"
      - "35729:35729"
      # - "5500:5500"
    volumes:
      - ./_config.yml:/site/_config.yml
      - ./tmp:/site/tmp
      - ./.firebaserc:/site/.firebaserc
      - ./analysis_options.yaml:/site/analysis_options.yaml
      - ./build.excerpt.yaml:/site/build.excerpt.yaml
      - ./examples:/site/examples
      - ./firebase.json:/site/firebase.json
      - ./Gemfile:/site/Gemfile
      - ./Gemfile.lock:/site/Gemfile.lock
      - ./Makefile:/site/Makefile
      - ./package-lock.json:/site/package-lock.json
      - ./package.json:/site/package.json
      - ./pubspec.yaml:/site/pubspec.yaml
      - ./site-shared:/site/site-shared
      - ./site-angular:/site/site-angular
      - ./src:/site/src
      - ./tool:/site/tool
